### ISSUE TITLE
[Insight] A GET action should not modify an existing resource - in src/…/Controller/TaskStatusController.php, line 209

### ISSUE THREAD

**Issue by danielnv18** [ParallelDevs/pdevspm#40]
**[in src/AppBundle/Controller/TaskStatusController.php, line 209](https://github.com/ParallelDevs/pdevspm/blob/3884b749500cd80e7551d401becb59f7e21c9a0d/src/AppBundle/Controller/TaskStatusController.php#L209)**

> The action `AppBundle\Controller\TaskStatusController::deleteAction` modifies an existing resource even though it can only be called with `GET` HTTP verb. Such an action should only accept `PUT`, `POST`, `DELETE`, or `PATCH` methods to avoid accidental data modification.

```php

        if (!$entity) {
           throw $this->createNotFoundException('Unable to find TaskStatus entity.');
        }

        $em->remove($entity);
        $em->flush();

        return $this->redirect($this->generateUrl('config_task_status'));
    }
}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1bca30ef-bc23-4178-8d14-aad1fb84a7f6/analyses/3?status=violations)_

**Comment by isaias1503** [comment]
Ready, I did the changes. Now, Its updated.
